eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver

#zipkin:
#  storage:
#    type: mysql

zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: localhost:9200