eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: eureka-ribbon-client

#stores:
#  ribbon:
#    listOfServers: example.com,google.com
#ribbon:
#  eureka:
#   enabled: false
#server:
#  port: 8769