spring:
  application:
    name: service-turbine
server:
  port: 8769
turbine:
  app-config: eureka-feign-client,eureka-ribbon-client
  cluster-name-expression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
